### ISSUE TITLE
Awesome packages, but where is the saf_util repository?

### ISSUE THREAD

**Issue by maelchiotti** [flutter-cavalry/saf_stream#1]
Hi, first of all thank you so much for these packages, they are very well designed and work perfectly! I was desperate to find a way to use SAF with Flutter and it took me a long time to find these gems.

I was wondering however where the GitHub repository of saf_util went, as I get a 404 error when trying to access it at the address specified on pub.dev ?

**Comment by mgenware** [comment]
@maelchiotti thanks for reporting this. I just realized saf_util was a private repo on my side. Updated it to public now :D
